# _target_: src.models.UNet3D.BasicUNet3D
_target_: src.models.UNet3D.BasicUNet3D

lr: 0.0005 # CHANGE HERE
out_channels: 2 # CHANGE HERE

extra_loss: null # hausdorff # CHANGE HERE

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0005 # CHANGE HERE
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5
monai: True
freeze_encoder: False

segm_encoder: False
encoder_chkp: /mrhome/vladyslavz/git/central-sulcus-analysis/logs_sst/via11-monai-BasicUnet-bvisaSim-skullstripped-noMaxPool/runs/2023-04-27_13-26-21/checkpoints/epoch-295_val_loss-0.171.ckpt

net:
  _target_: monai.networks.nets.basic_unet.BasicUNet
  spatial_dims: 3
  in_channels: 1
  out_channels: 2
  features:
    - 16
    - 32
    - 64
    - 128
    - 256
    - 32
# loss_function:
#   _target_: torch.nn.CrossEntropyLoss
#   # ignore_index: 0


# loss_function:
#   _target_: torch.nn.CrossEntropyLoss
#   reduction: sum


loss_function:
  _target_: monai.losses.TverskyLoss
  to_onehot_y: True # should be true of include_background is false
  # because first channel from target_y is excluded
  softmax: True
  # jaccard: False
  include_background: True
  # lambda_dice: 1.
  # lambda_ce: 0.