_target_: src.models.UNet3D.BasicUNet3D

lr: 0.001 # CHANGE HERE
out_channels: 65 # CHANGE HERE
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001 # AND HERE MAYBE???????
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: monai.networks.nets.BasicUNet
  spatial_dims: 3
  in_channels: 1
  out_channels: 65 # CHANGE HERE
  features:
    - 32
    - 32
    - 64
    - 128
    - 256
    - 32

# loss_function:
#   _target_: torch.nn.CrossEntropyLoss
#   ignore_index: 0

loss_function:
  _target_: monai.losses.MaskedDiceLoss
  to_onehot_y: True # should be true of include_background is false
  # because first channel from target_y is excluded
  softmax: True
  jaccard: False
  include_background: False