_target_: src.models.UNet3D.BasicUNet3D

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.01
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: monai.networks.nets.BasicUNet
  spatial_dims: 3
  in_channels: 1
  out_channels: 2
  features:
    - 32
    - 32
    - 64
    - 128
    - 256
    - 32

loss_function:
  _target_: monai.losses.DiceLoss
  to_onehot_y: True
  include_background: True