_target_: src.models.UNet3D.BasicUNet3D

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.unet3d.model.UNet3D
  # spatial_dims: 3
  in_channels: 1
  out_channels: 63
  final_sigmoid: False
  f_maps:
    - 8
    - 16
    - 32

loss_function:
  _target_: torch.nn.CrossEntropyLoss
  # ignore_index: 0
  # to_onehot_y: True
  # include_background: True