_target_: src.models.simclr_segm.SimCLRSegm
max_epochs: 1000 # CHANGED HERE AND IN TRAINER/DEFAULT.YAML
hidden_dim: 128
lr: 0.0005 # CHANGE HERE
temperature: 0.05
weight_decay: 1e-4
img_dim: 256
dice_weight: 0.1

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5

unet:
  _target_: src.models.monai_impl.BasicUNetEncoderDecoder
  spatial_dims: 3
  in_channels: 1
  out_channels: 2
  features:
    - 16
    - 32
    - 64
    - 128
    - 256
    - 32
segm_loss:
  # _target_: torch.nn.CrossEntropyLoss
  _target_: monai.losses.DiceLoss
  to_onehot_y: True # should be true of include_background is false
  # because first channel from target_y is excluded
  softmax: True
  include_background: True

  # _target_: monai.losses.TverskyLoss
  # to_onehot_y: True # should be true of include_background is false
  # # because first channel from target_y is excluded
  # softmax: True
  # # jaccard: False
  # include_background: True
  # # lambda_dice: 1.
  # # lambda_ce: 0.