_target_: src.models.simclr.SimCLR
max_epochs: 1000 # CHANGED HERE AND IN TRAINER/DEFAULT.YAML
hidden_dim: 128
lr: 0.0001 # CHANGE HERE
temperature: 0.07
weight_decay: 1e-4
img_dim: 256
# dice_weight: 0.5

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5

# encoder:
#   _target_: src.models.unet3d.model_encoders.UNet3D
#   in_channels: 1
#   out_channels: 2
#   # decoder_encoder: True
#   only_encoder: True
#   f_maps:
#     - 16
#     - 32
#     - 64
#     - 128
#     - 256
#     - 512

encoder:
  _target_: src.models.monai_impl.BasicUNetEncoder
  spatial_dims: 3
  in_channels: 1
  out_channels: 2
  features:
    - 16
    - 32
    - 64
    - 128
    - 256
    - 32