_target_: src.models.simclr.SimCLR
max_epochs: 500 # CHANGED HERE AND IN TRAINER/DEFAULT.YAML
hidden_dim: 128
lr: 0.001 # CHANGE HERE
temperature: 0.07
weight_decay: 1e-4
img_dim: 128
# dice_weight: 0.5

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001 # CHANGE HERE

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5

encoder:
  _target_: src.models.unet3d.model_encoders.UNet3D
  in_channels: 1
  out_channels: 3
  # decoder_encoder: True
  only_encoder: True
  f_maps:
    - 16
    - 32
    - 64
    - 128
    - 256
    - 512