defaults:
  - model_checkpoint.yaml
  - rich_progress_bar.yaml
  - device_stats.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch-{epoch:03d}_valacc_top5-{val_acc_top1:.3f}"
  monitor: "val_acc_top1"
  mode: "max"
  save_top_k: 3
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val_acc_top1"
  patience: 100
  mode: "max"

model_summary:
  max_depth: -1
