defaults:
  - model_checkpoint.yaml
  # - early_stopping.yaml
  # - model_summary.yaml
  - rich_progress_bar.yaml
  - device_stats.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch-{epoch:03d}-val_mse-{val/mse:.4f}"
  monitor: "val/mse"
  mode: "min"
  save_top_k: 3
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/mse"
  patience: 100
  mode: "min"

model_summary:
  max_depth: -1
