defaults:
  - model_checkpoint.yaml
  - rich_progress_bar.yaml
  - device_stats.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch-{epoch:03d}_val_loss-{val_loss:.3f}"
  monitor: "val_loss"
  mode: "min"
  save_top_k: 3
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val_loss"
  patience: 100
  mode: "max"

model_summary:
  max_depth: -1
