# https://pytorch-lightning.readthedocs.io/en/stable/tuning/profiler_basic.html

device_stat:
  _target_: pytorch_lightning.callbacks.DeviceStatsMonitor
  # max_depth: 1 # the maximum depth of layer nesting that the summary will include
