# @package _global_

# task name, determines output directory path
task_name: "CS1x_bvisaSST_tverskyLoss_monaBasicUnet-fullFinetune"

# tags to help you identify your experiments
tags: ["dev"]

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: False

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: null


# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: bvisa_cs_augm.yaml
  - model: basicUNet.yaml
  - callbacks: default.yaml
  - logger: tensorboard # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

  # config for hyperparameter optimization
  - hparams_search: null

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null


